//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SMO.SMS_VNPT_GW {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bsmswsSoap", Namespace="http://tempuri.org/")]
    public partial class bsmsws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendBrandSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBrandSmsQCOperationCompleted;
        
        private System.Threading.SendOrPostCallback UPDATE_STATUSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public bsmsws() {
            this.Url = global::SMO.Properties.Settings.Default.SMO_SMS_VNPT_GW_bsmsws;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendBrandSmsCompletedEventHandler SendBrandSmsCompleted;
        
        /// <remarks/>
        public event SendBrandSmsQCCompletedEventHandler SendBrandSmsQCCompleted;
        
        /// <remarks/>
        public event UPDATE_STATUSCompletedEventHandler UPDATE_STATUSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBrandSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendBrandSms(string username, string password, string phonenumber, string message, string brandname, int loaitin) {
            object[] results = this.Invoke("SendBrandSms", new object[] {
                        username,
                        password,
                        phonenumber,
                        message,
                        brandname,
                        loaitin});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendBrandSmsAsync(string username, string password, string phonenumber, string message, string brandname, int loaitin) {
            this.SendBrandSmsAsync(username, password, phonenumber, message, brandname, loaitin, null);
        }
        
        /// <remarks/>
        public void SendBrandSmsAsync(string username, string password, string phonenumber, string message, string brandname, int loaitin, object userState) {
            if ((this.SendBrandSmsOperationCompleted == null)) {
                this.SendBrandSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBrandSmsOperationCompleted);
            }
            this.InvokeAsync("SendBrandSms", new object[] {
                        username,
                        password,
                        phonenumber,
                        message,
                        brandname,
                        loaitin}, this.SendBrandSmsOperationCompleted, userState);
        }
        
        private void OnSendBrandSmsOperationCompleted(object arg) {
            if ((this.SendBrandSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBrandSmsCompleted(this, new SendBrandSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBrandSmsQC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendBrandSmsQC(string username, string password, string billid, string billname, string phonenumber, string message, string brandname, string Sendtime) {
            object[] results = this.Invoke("SendBrandSmsQC", new object[] {
                        username,
                        password,
                        billid,
                        billname,
                        phonenumber,
                        message,
                        brandname,
                        Sendtime});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendBrandSmsQCAsync(string username, string password, string billid, string billname, string phonenumber, string message, string brandname, string Sendtime) {
            this.SendBrandSmsQCAsync(username, password, billid, billname, phonenumber, message, brandname, Sendtime, null);
        }
        
        /// <remarks/>
        public void SendBrandSmsQCAsync(string username, string password, string billid, string billname, string phonenumber, string message, string brandname, string Sendtime, object userState) {
            if ((this.SendBrandSmsQCOperationCompleted == null)) {
                this.SendBrandSmsQCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBrandSmsQCOperationCompleted);
            }
            this.InvokeAsync("SendBrandSmsQC", new object[] {
                        username,
                        password,
                        billid,
                        billname,
                        phonenumber,
                        message,
                        brandname,
                        Sendtime}, this.SendBrandSmsQCOperationCompleted, userState);
        }
        
        private void OnSendBrandSmsQCOperationCompleted(object arg) {
            if ((this.SendBrandSmsQCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBrandSmsQCCompleted(this, new SendBrandSmsQCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_STATUS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UPDATE_STATUS(string username, string password, string idrequest, string brandname) {
            object[] results = this.Invoke("UPDATE_STATUS", new object[] {
                        username,
                        password,
                        idrequest,
                        brandname});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATE_STATUSAsync(string username, string password, string idrequest, string brandname) {
            this.UPDATE_STATUSAsync(username, password, idrequest, brandname, null);
        }
        
        /// <remarks/>
        public void UPDATE_STATUSAsync(string username, string password, string idrequest, string brandname, object userState) {
            if ((this.UPDATE_STATUSOperationCompleted == null)) {
                this.UPDATE_STATUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATE_STATUSOperationCompleted);
            }
            this.InvokeAsync("UPDATE_STATUS", new object[] {
                        username,
                        password,
                        idrequest,
                        brandname}, this.UPDATE_STATUSOperationCompleted, userState);
        }
        
        private void OnUPDATE_STATUSOperationCompleted(object arg) {
            if ((this.UPDATE_STATUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATE_STATUSCompleted(this, new UPDATE_STATUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendBrandSmsCompletedEventHandler(object sender, SendBrandSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBrandSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBrandSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendBrandSmsQCCompletedEventHandler(object sender, SendBrandSmsQCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBrandSmsQCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBrandSmsQCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UPDATE_STATUSCompletedEventHandler(object sender, UPDATE_STATUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATE_STATUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATE_STATUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591