//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMO.TGBX_GW {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endpoint_01Result", Namespace="http://schemas.datacontract.org/2004/07/GW_SMO.Database")]
    [System.SerializableAttribute()]
    public partial class Endpoint_01Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DuXuatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHangHoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoLenhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ThoiGianCuoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ThoiGianDauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TongXuatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TrangThai_TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DuXuat {
            get {
                return this.DuXuatField;
            }
            set {
                if ((this.DuXuatField.Equals(value) != true)) {
                    this.DuXuatField = value;
                    this.RaisePropertyChanged("DuXuat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHangHoa {
            get {
                return this.MaHangHoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHangHoaField, value) != true)) {
                    this.MaHangHoaField = value;
                    this.RaisePropertyChanged("MaHangHoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoLenh {
            get {
                return this.SoLenhField;
            }
            set {
                if ((object.ReferenceEquals(this.SoLenhField, value) != true)) {
                    this.SoLenhField = value;
                    this.RaisePropertyChanged("SoLenh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThoiGianCuoi {
            get {
                return this.ThoiGianCuoiField;
            }
            set {
                if ((this.ThoiGianCuoiField.Equals(value) != true)) {
                    this.ThoiGianCuoiField = value;
                    this.RaisePropertyChanged("ThoiGianCuoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThoiGianDau {
            get {
                return this.ThoiGianDauField;
            }
            set {
                if ((this.ThoiGianDauField.Equals(value) != true)) {
                    this.ThoiGianDauField = value;
                    this.RaisePropertyChanged("ThoiGianDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TongXuat {
            get {
                return this.TongXuatField;
            }
            set {
                if ((this.TongXuatField.Equals(value) != true)) {
                    this.TongXuatField = value;
                    this.RaisePropertyChanged("TongXuat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrangThai_Time {
            get {
                return this.TrangThai_TimeField;
            }
            set {
                if ((this.TrangThai_TimeField.Equals(value) != true)) {
                    this.TrangThai_TimeField = value;
                    this.RaisePropertyChanged("TrangThai_Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endpoint_02_ViewTableResult", Namespace="http://schemas.datacontract.org/2004/07/GW_SMO.Database")]
    [System.SerializableAttribute()]
    public partial class Endpoint_02_ViewTableResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhuongTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoLenhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThai_SMOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaPhuongTien {
            get {
                return this.MaPhuongTienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhuongTienField, value) != true)) {
                    this.MaPhuongTienField = value;
                    this.RaisePropertyChanged("MaPhuongTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoLenh {
            get {
                return this.SoLenhField;
            }
            set {
                if ((object.ReferenceEquals(this.SoLenhField, value) != true)) {
                    this.SoLenhField = value;
                    this.RaisePropertyChanged("SoLenh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThai_SMO {
            get {
                return this.TrangThai_SMOField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThai_SMOField, value) != true)) {
                    this.TrangThai_SMOField = value;
                    this.RaisePropertyChanged("TrangThai_SMO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TGBX_GW.IGW_SMO")]
    public interface IGW_SMO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_01", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_01Response")]
        SMO.TGBX_GW.Endpoint_01Result[] Endpoint_01(string deliveries_string);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_01", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_01Response")]
        System.Threading.Tasks.Task<SMO.TGBX_GW.Endpoint_01Result[]> Endpoint_01Async(string deliveries_string);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_02", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_02Response")]
        string Endpoint_02(string deliveries_string, string vehicle_number, string smo_status, System.DateTime ngayvaokho, string nguoilaixe, long sochuyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_02", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_02Response")]
        System.Threading.Tasks.Task<string> Endpoint_02Async(string deliveries_string, string vehicle_number, string smo_status, System.DateTime ngayvaokho, string nguoilaixe, long sochuyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_02_ViewTable", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_02_ViewTableResponse")]
        SMO.TGBX_GW.Endpoint_02_ViewTableResult[] Endpoint_02_ViewTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGW_SMO/Endpoint_02_ViewTable", ReplyAction="http://tempuri.org/IGW_SMO/Endpoint_02_ViewTableResponse")]
        System.Threading.Tasks.Task<SMO.TGBX_GW.Endpoint_02_ViewTableResult[]> Endpoint_02_ViewTableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGW_SMOChannel : SMO.TGBX_GW.IGW_SMO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GW_SMOClient : System.ServiceModel.ClientBase<SMO.TGBX_GW.IGW_SMO>, SMO.TGBX_GW.IGW_SMO {
        
        public GW_SMOClient() {
        }
        
        public GW_SMOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GW_SMOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GW_SMOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GW_SMOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMO.TGBX_GW.Endpoint_01Result[] Endpoint_01(string deliveries_string) {
            return base.Channel.Endpoint_01(deliveries_string);
        }
        
        public System.Threading.Tasks.Task<SMO.TGBX_GW.Endpoint_01Result[]> Endpoint_01Async(string deliveries_string) {
            return base.Channel.Endpoint_01Async(deliveries_string);
        }
        
        public string Endpoint_02(string deliveries_string, string vehicle_number, string smo_status, System.DateTime ngayvaokho, string nguoilaixe, long sochuyen) {
            return base.Channel.Endpoint_02(deliveries_string, vehicle_number, smo_status, ngayvaokho, nguoilaixe, sochuyen);
        }
        
        public System.Threading.Tasks.Task<string> Endpoint_02Async(string deliveries_string, string vehicle_number, string smo_status, System.DateTime ngayvaokho, string nguoilaixe, long sochuyen) {
            return base.Channel.Endpoint_02Async(deliveries_string, vehicle_number, smo_status, ngayvaokho, nguoilaixe, sochuyen);
        }
        
        public SMO.TGBX_GW.Endpoint_02_ViewTableResult[] Endpoint_02_ViewTable() {
            return base.Channel.Endpoint_02_ViewTable();
        }
        
        public System.Threading.Tasks.Task<SMO.TGBX_GW.Endpoint_02_ViewTableResult[]> Endpoint_02_ViewTableAsync() {
            return base.Channel.Endpoint_02_ViewTableAsync();
        }
    }
}
