//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SMO.EGAS_GW {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EGASWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EGASWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_transactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMO_transactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EGASWebService() {
            this.Url = global::SMO.Properties.Settings.Default.SMO_EGAS_GW_EGASWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_transactionCompletedEventHandler get_transactionCompleted;
        
        /// <remarks/>
        public event SMO_transactionCompletedEventHandler SMO_transactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_transaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_transaction(string username, string pass, string fromdate, string todate, string strpos, string tran_type) {
            object[] results = this.Invoke("get_transaction", new object[] {
                        username,
                        pass,
                        fromdate,
                        todate,
                        strpos,
                        tran_type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_transactionAsync(string username, string pass, string fromdate, string todate, string strpos, string tran_type) {
            this.get_transactionAsync(username, pass, fromdate, todate, strpos, tran_type, null);
        }
        
        /// <remarks/>
        public void get_transactionAsync(string username, string pass, string fromdate, string todate, string strpos, string tran_type, object userState) {
            if ((this.get_transactionOperationCompleted == null)) {
                this.get_transactionOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_transactionOperationCompleted);
            }
            this.InvokeAsync("get_transaction", new object[] {
                        username,
                        pass,
                        fromdate,
                        todate,
                        strpos,
                        tran_type}, this.get_transactionOperationCompleted, userState);
        }
        
        private void Onget_transactionOperationCompleted(object arg) {
            if ((this.get_transactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_transactionCompleted(this, new get_transactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMO_transaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMO_transaction(string username, string pass, string transportnumber) {
            object[] results = this.Invoke("SMO_transaction", new object[] {
                        username,
                        pass,
                        transportnumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMO_transactionAsync(string username, string pass, string transportnumber) {
            this.SMO_transactionAsync(username, pass, transportnumber, null);
        }
        
        /// <remarks/>
        public void SMO_transactionAsync(string username, string pass, string transportnumber, object userState) {
            if ((this.SMO_transactionOperationCompleted == null)) {
                this.SMO_transactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMO_transactionOperationCompleted);
            }
            this.InvokeAsync("SMO_transaction", new object[] {
                        username,
                        pass,
                        transportnumber}, this.SMO_transactionOperationCompleted, userState);
        }
        
        private void OnSMO_transactionOperationCompleted(object arg) {
            if ((this.SMO_transactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMO_transactionCompleted(this, new SMO_transactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void get_transactionCompletedEventHandler(object sender, get_transactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_transactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_transactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SMO_transactionCompletedEventHandler(object sender, SMO_transactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMO_transactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMO_transactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591