using SMO.Core.Common;

namespace SMO.Core.Entities.MD
{
    public class T_MD_OTHER_PROFIT_CENTER : CoreCenter
    {
        // code and parent code of profit center will be generate when create tree
        // it will be generated by COMPANY_CODE + PROJECT_CODE + CENTER_CODE
        // real center code to mapping stored in REAL_CENTER_CODE
        public virtual string COMPANY_CODE { get; set; }
        public virtual string PROJECT_CODE { get; set; }
        public virtual T_MD_COMPANY Company { get; set; }
        public virtual T_MD_PROJECT Project { get; set; }
    }
}
